version: "3.7"
services:
  mysql-db:
    image: mysql:8.0.40-debian
    container_name: mysql-db
    hostname: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - type: volume
        source: staff-vol
        target: /var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"

volumes: 
  staff-vol: